### ISSUE TITLE
The promise rejected with the reason when scanning QR

### ISSUE THREAD

**Issue by irq20xdfr** [orkestral/superchats#14]
When scanning the QR it shows this stacktrace

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: _0x8337b6[_0x7e8585(...)] is not a function
    at EventEmitter.<anonymous> (/Users/danielf/Documents/MadRestaurant/node_modules/superchats/dist/initializer.js:1:8903)
    at EventEmitter.emit (node:events:402:35)
    at EventEmitter.emit (node:domain:475:12)
    at _0x2980d2 (/Users/danielf/Documents/MadRestaurant/node_modules/superchats/dist/Connection/socket.js:1:14361)
    at WebSocket.<anonymous> (/uperchats/dist/Connection/socket.js:1:20312)
    
    
And WhatsApp QR keeps waiting.

**Comment by pasiga** [comment]
I have the same problem

**Comment by irq20xdfr** [comment]
Just restar the process when WhatsApp is loading the QR info

**Comment by pasiga** [comment]
no start, , it is waiting

NFO [test]: connected to SuperChats Nitro
INFO [test]: logging in...
INFO [test]: Valid license, thanks for using !!!
INFO [test]: token removed or expired
